# Generated by Django 3.2 on 2021-10-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationuser',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
