# Generated by Django 3.2.7 on 2021-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_locationuser_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationuser',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
