# Generated by Django 3.2.7 on 2021-09-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
